theta_arr = -90:18:90;
phi_arr = -90:18:90;
[theta_grid, phi_grid] = meshgrid(theta_arr, phi_arr);
theta_grid = theta_grid / 180 * pi;
phi_grid = phi_grid / 180 * pi;
%%
% coord = SO3(1,-0.3,1);
%% 
funcval = KentFunc(1, 1, 2, 0.1, 0.2, 3, theta_grid(:),phi_grid(:));
funcval = funcval + randn(size(funcval)) * 0.1 ;
funcval2 = funcval + randn(size(funcval)) * 0.1 ;
funcmap = reshape(funcval, size(theta_grid));
%%
figure
imagesc(theta_arr, phi_arr, funcmap)
%%
ft = fittype( @(theta, phi, psi, kappa, beta, A, x, y) KentFunc(theta, phi, psi, kappa, beta, A, x, y), ...
    'independent', {'x', 'y'},'dependent',{'z'});
    %'problem', {'theta', 'phi', 'psi', 'kappa', 'beta', 'A'}, ...
Parameter = fit( [theta_grid(:), phi_grid(:);theta_grid(:), phi_grid(:)], [funcval; funcval2], ft, ...
                'StartPoint', [0, 0, pi/2, 0.1, 0.1, 0.1], ...
                'Lower', [-pi, -pi/2,  0, -Inf,   0,   0], ...
                'Upper', [ pi,  pi/2,  pi,  Inf, Inf, Inf])%, ...
                %'Robust', 'LAR' )

%%
Parameter = fit( [theta_grid(:), phi_grid(:)], funcval, ft, ...
                'StartPoint', [0, 0, pi/2, 0.1, 0.1, 0.1], ...
                'Lower', [-pi, -pi/2,  0, -Inf,   0,   0], ...
                'Upper', [ pi,  pi/2,  pi,  Inf, Inf, Inf], ...
                'Robust', 'LAR' )
